use COMERCIO_OLTP
go

SELECT COUNT(*) FROM CLIENTE
go

SELECT COUNT(*) FROM ENDERECO
go

SELECT C.NOME, E.RUA
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
GO

SELECT COUNT(*) AS QUANTIDADE
FROM CLIENTE C
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE
GO